title: Ricardo Gonz√°lez Gil
#logo: /.../headshot_circle.png
#description: text below image
show_downloads: true #if false, downloads don't show (or commented out)
remote_theme: pages-themes/minimal@v0.2.0  #https://pages.github.com/themes/
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

